{{- if .Values.ingress.enabled -}}
{{- $fullName := include "vaultwarden-k8s.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-k8s.name" . }}
    helm.sh/chart: {{ include "vaultwarden-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  defaultBackend:
    service:
      name: {{ $fullName }}
      port:
        number: 80
  ingressClassName: nginx
  rules:
    - host: {{ $.Values.ingress.hosts }}
{{- end }}
